### ISSUE TITLE
无法转跳

### ISSUE THREAD

**Issue by a675286277** [wangxinleo/UpGoRemove_Flask#2]
您好  请问一下大佬我安装你的教程搭建好了服务器和数据库后  主页能正常出来  但是为什么填入了密匙后还是主页 没有转跳呢  附上地址http://118.31.1.29:5000/    万分感谢

**Comment by wangxinleo** [comment]
感谢反馈这个BUG，由于这个功能已经被体验版的读取数据库中的密钥替代，所以一直没有遗漏私钥上传的问题，我将会在近期修复这个问题:heart:，非常感谢您关注这个项目~比心:heart:

**Comment by wangxinleo** [comment]
问题已经解决，我已经改变了密钥存储逻辑，取消了体验版按钮，添加密钥后会直接上传至数据库保存方便下次提取，下载新版本的代码部署即可:)
